---
title: "R Notebook"
output: html_notebook
---

```{r}
data = data(stackloss)
data <- stackloss
head(data)
```
# a) Scatterplot
```{r}
pairs(stackloss, main = "Scatter Plot")

```

# b) Frequentist regression
```{r}
freq_reg = lm(stack.loss ~ ., data = data)
summary(freq_reg)

print("confidence intervals for parameters")
confint(freq_reg,level=0.95)

print("prediction vs true value")
cbind(data["stack.loss"],predict(freq_reg))
rmse <- sqrt(mean((data[["stack.loss"]] - predict(freq_reg))^2))
print(rmse)


print("Confidence Intervals")
predict(freq_reg,newdata = data.frame(Air.Flow=60,Water.Temp=20,Acid.Conc.=80),interval = "confidence",level = 0.95)

print("Prediction Interval")
predict(freq_reg,newdata = data.frame(Air.Flow=60,Water.Temp=20,Acid.Conc.=80),interval = "prediction",level = 0.95)


```

# c) Bayesian regression
```{r}
library(MCMCpack)
burnin = 1000
mcmc = 10000

# train model
bayes_reg = MCMCregress(stack.loss ~ ., data = data, burnin = burnin, mcmc = mcmc)
summary(bayes_reg)

# plot trace
plot(bayes_reg)

# posterior mean & medians
print("posterior mean/median")

apply(bayes_reg, 2, mean)
apply(bayes_reg, 2, median)

# credible intervals
print("confidence intervals for parameters")
apply(bayes_reg, 2, quantile, probs= c(0.025, 0.975))

# Predictions 
print("predict")

betas = bayes_reg[,1:4]
beta_mean = apply(betas, 2, mean)
n = nrow(data)
X <- cbind(rep(1,n),
           as.numeric(data[["Air.Flow"]]), 
           as.numeric(data[["Water.Temp"]]), 
           as.numeric(data[["Acid.Conc."]]))
y_pred = X %*% beta_mean
compare_pred = cbind(data["stack.loss"], y_pred)

rmse <- sqrt(mean((data[["stack.loss"]] - y_pred)^2))
print(rmse)

# Confidence intervals
print("confidence intervals for regression")
X_new = c(1, 60, 20, 80)
y_pred_new_mean = X_new %*% t(betas)
quantile(y_pred_new_mean, probs = c(0.025, 0.975))

# Predictive Interval
print("predictive intervals for predictions")
sigma2 = bayes_reg[,5]
y_pred_new_predInterval = rnorm(mcmc, y_pred_new_mean, sqrt(sigma2))
quantile(y_pred_new_predInterval, probs = c(0.025, 0.975))

```

